version: "3.3"

services:
#  api_keys:
#    restart: always
#    container_name: api_keys
#    build:
#      context: .
#      dockerfile: ./src/test/resources/Dockerfile-api-keys
#    environment:
#      MONGO_DATABASE_URL: mongodb://keys_mongodb:27017
#      MONGO_DATABASE_NAME: api_keys
#    depends_on:
#      - mongo-setup
#    ports:
#      - "8080:8080"

  keys-mongodb:
    restart: always
    container_name: keys_mongodb
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=keys
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
#    networks:
#      - gateway_main-net

volumes:
  mongo_data:

#networks:
#  gateway_main-net:
#    external: true