# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from swagger_server.proto import trips_pb2 as swagger__server_dot_proto_dot_trips__pb2


class TripsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTrip = channel.unary_unary(
                '/trips.Trips/AddTrip',
                request_serializer=swagger__server_dot_proto_dot_trips__pb2.Trip.SerializeToString,
                response_deserializer=swagger__server_dot_proto_dot_trips__pb2.TripID.FromString,
                )
        self.GetLocationById = channel.unary_unary(
                '/trips.Trips/GetLocationById',
                request_serializer=swagger__server_dot_proto_dot_trips__pb2.LocationID.SerializeToString,
                response_deserializer=swagger__server_dot_proto_dot_trips__pb2.Location.FromString,
                )
        self.GetLocationByCity = channel.unary_unary(
                '/trips.Trips/GetLocationByCity',
                request_serializer=swagger__server_dot_proto_dot_trips__pb2.City.SerializeToString,
                response_deserializer=swagger__server_dot_proto_dot_trips__pb2.LocationID.FromString,
                )
        self.RemoveTrip = channel.unary_unary(
                '/trips.Trips/RemoveTrip',
                request_serializer=swagger__server_dot_proto_dot_trips__pb2.TripID.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateTrip = channel.unary_unary(
                '/trips.Trips/UpdateTrip',
                request_serializer=swagger__server_dot_proto_dot_trips__pb2.UpdateTripRequest.SerializeToString,
                response_deserializer=swagger__server_dot_proto_dot_trips__pb2.Trip.FromString,
                )
        self.GetCountTripsInLocation = channel.unary_unary(
                '/trips.Trips/GetCountTripsInLocation',
                request_serializer=swagger__server_dot_proto_dot_trips__pb2.GetCountTripsInLocationRequest.SerializeToString,
                response_deserializer=swagger__server_dot_proto_dot_trips__pb2.GetCountTripsInLocationResponse.FromString,
                )


class TripsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTrip(self, request, context):
        """Add a trip to the data used to calculate the value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocationById(self, request, context):
        """Find location description by ID

        Returns LocationID object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocationByCity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTrip(self, request, context):
        """Remove a trip in the data used to calculate the value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTrip(self, request, context):
        """Change a trip in the data used to calculate the value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCountTripsInLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TripsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTrip': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTrip,
                    request_deserializer=swagger__server_dot_proto_dot_trips__pb2.Trip.FromString,
                    response_serializer=swagger__server_dot_proto_dot_trips__pb2.TripID.SerializeToString,
            ),
            'GetLocationById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocationById,
                    request_deserializer=swagger__server_dot_proto_dot_trips__pb2.LocationID.FromString,
                    response_serializer=swagger__server_dot_proto_dot_trips__pb2.Location.SerializeToString,
            ),
            'GetLocationByCity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocationByCity,
                    request_deserializer=swagger__server_dot_proto_dot_trips__pb2.City.FromString,
                    response_serializer=swagger__server_dot_proto_dot_trips__pb2.LocationID.SerializeToString,
            ),
            'RemoveTrip': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTrip,
                    request_deserializer=swagger__server_dot_proto_dot_trips__pb2.TripID.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateTrip': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTrip,
                    request_deserializer=swagger__server_dot_proto_dot_trips__pb2.UpdateTripRequest.FromString,
                    response_serializer=swagger__server_dot_proto_dot_trips__pb2.Trip.SerializeToString,
            ),
            'GetCountTripsInLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCountTripsInLocation,
                    request_deserializer=swagger__server_dot_proto_dot_trips__pb2.GetCountTripsInLocationRequest.FromString,
                    response_serializer=swagger__server_dot_proto_dot_trips__pb2.GetCountTripsInLocationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trips.Trips', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Trips(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTrip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trips.Trips/AddTrip',
            swagger__server_dot_proto_dot_trips__pb2.Trip.SerializeToString,
            swagger__server_dot_proto_dot_trips__pb2.TripID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocationById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trips.Trips/GetLocationById',
            swagger__server_dot_proto_dot_trips__pb2.LocationID.SerializeToString,
            swagger__server_dot_proto_dot_trips__pb2.Location.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocationByCity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trips.Trips/GetLocationByCity',
            swagger__server_dot_proto_dot_trips__pb2.City.SerializeToString,
            swagger__server_dot_proto_dot_trips__pb2.LocationID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveTrip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trips.Trips/RemoveTrip',
            swagger__server_dot_proto_dot_trips__pb2.TripID.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTrip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trips.Trips/UpdateTrip',
            swagger__server_dot_proto_dot_trips__pb2.UpdateTripRequest.SerializeToString,
            swagger__server_dot_proto_dot_trips__pb2.Trip.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCountTripsInLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trips.Trips/GetCountTripsInLocation',
            swagger__server_dot_proto_dot_trips__pb2.GetCountTripsInLocationRequest.SerializeToString,
            swagger__server_dot_proto_dot_trips__pb2.GetCountTripsInLocationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
