# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TripUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pickup_datetime: datetime=None, dropoff_datetime: datetime=None, pickup_location_id: float=None, dropoff_location_id: float=None, passenger_count: float=1):  # noqa: E501
        """TripUpdate - a model defined in Swagger

        :param pickup_datetime: The pickup_datetime of this TripUpdate.  # noqa: E501
        :type pickup_datetime: datetime
        :param dropoff_datetime: The dropoff_datetime of this TripUpdate.  # noqa: E501
        :type dropoff_datetime: datetime
        :param pickup_location_id: The pickup_location_id of this TripUpdate.  # noqa: E501
        :type pickup_location_id: float
        :param dropoff_location_id: The dropoff_location_id of this TripUpdate.  # noqa: E501
        :type dropoff_location_id: float
        :param passenger_count: The passenger_count of this TripUpdate.  # noqa: E501
        :type passenger_count: float
        """
        self.swagger_types = {
            'pickup_datetime': datetime,
            'dropoff_datetime': datetime,
            'pickup_location_id': float,
            'dropoff_location_id': float,
            'passenger_count': float
        }

        self.attribute_map = {
            'pickup_datetime': 'pickup_datetime',
            'dropoff_datetime': 'dropoff_datetime',
            'pickup_location_id': 'pickup_location_id',
            'dropoff_location_id': 'dropoff_location_id',
            'passenger_count': 'passenger_count'
        }
        self._pickup_datetime = pickup_datetime
        self._dropoff_datetime = dropoff_datetime
        self._pickup_location_id = pickup_location_id
        self._dropoff_location_id = dropoff_location_id
        self._passenger_count = passenger_count

    @classmethod
    def from_dict(cls, dikt) -> 'TripUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TripUpdate of this TripUpdate.  # noqa: E501
        :rtype: TripUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pickup_datetime(self) -> datetime:
        """Gets the pickup_datetime of this TripUpdate.


        :return: The pickup_datetime of this TripUpdate.
        :rtype: datetime
        """
        return self._pickup_datetime

    @pickup_datetime.setter
    def pickup_datetime(self, pickup_datetime: datetime):
        """Sets the pickup_datetime of this TripUpdate.


        :param pickup_datetime: The pickup_datetime of this TripUpdate.
        :type pickup_datetime: datetime
        """

        self._pickup_datetime = pickup_datetime

    @property
    def dropoff_datetime(self) -> datetime:
        """Gets the dropoff_datetime of this TripUpdate.


        :return: The dropoff_datetime of this TripUpdate.
        :rtype: datetime
        """
        return self._dropoff_datetime

    @dropoff_datetime.setter
    def dropoff_datetime(self, dropoff_datetime: datetime):
        """Sets the dropoff_datetime of this TripUpdate.


        :param dropoff_datetime: The dropoff_datetime of this TripUpdate.
        :type dropoff_datetime: datetime
        """

        self._dropoff_datetime = dropoff_datetime

    @property
    def pickup_location_id(self) -> float:
        """Gets the pickup_location_id of this TripUpdate.


        :return: The pickup_location_id of this TripUpdate.
        :rtype: float
        """
        return self._pickup_location_id

    @pickup_location_id.setter
    def pickup_location_id(self, pickup_location_id: float):
        """Sets the pickup_location_id of this TripUpdate.


        :param pickup_location_id: The pickup_location_id of this TripUpdate.
        :type pickup_location_id: float
        """

        self._pickup_location_id = pickup_location_id

    @property
    def dropoff_location_id(self) -> float:
        """Gets the dropoff_location_id of this TripUpdate.


        :return: The dropoff_location_id of this TripUpdate.
        :rtype: float
        """
        return self._dropoff_location_id

    @dropoff_location_id.setter
    def dropoff_location_id(self, dropoff_location_id: float):
        """Sets the dropoff_location_id of this TripUpdate.


        :param dropoff_location_id: The dropoff_location_id of this TripUpdate.
        :type dropoff_location_id: float
        """

        self._dropoff_location_id = dropoff_location_id

    @property
    def passenger_count(self) -> float:
        """Gets the passenger_count of this TripUpdate.


        :return: The passenger_count of this TripUpdate.
        :rtype: float
        """
        return self._passenger_count

    @passenger_count.setter
    def passenger_count(self, passenger_count: float):
        """Sets the passenger_count of this TripUpdate.


        :param passenger_count: The passenger_count of this TripUpdate.
        :type passenger_count: float
        """

        self._passenger_count = passenger_count
