apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
    purpose: monitoring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      purpose: monitoring-service
  template:
    metadata:
      labels:
        app: grafana
        purpose: monitoring-service
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
    purpose: monitoring-service
  ports:
    - name: grafanaui
      protocol: TCP
      port: 3000
      targetPort: 3000