apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    # Uncomment for authentication
    # nginx.ingress.kubernetes.io/auth-url: http://api_keys/keys/consume
spec:
  ingressClassName: nginx
  tls:
  - secretName: ingress-secret
  rules:
  - http:
      paths:
      - path: /trip
        pathType: Prefix
        backend:
          service:
            name: trips-service
            port:
              number: 8080
      - path: /tripCount
        pathType: Prefix
        backend:
          service:
            name: trips-service
            port:
              number: 8080
