apiVersion: v1
kind: ConfigMap
metadata:
  name: keys-configmap
  namespace: service
data:
  database_host: mongo-keys-service.database
  database_port: "27017"
  database_name: api_keys
  acl.yaml: |
    endpoints:
      /trip:
        POST:
          ADMIN: 0
      /trip/{trip_id}:
        PUT:
          ADMIN: 0
        DELETE:
          ADMIN: 0
      /trip/location/{location_id}:
        GET:
          ADMIN: 0
          CONSUMER: 1
      /tripCount/location/{location_id}:
        GET:
          ADMIN: 0
          CONSUMER: 1
      /key:
        GET:
          ADMIN: 0
          CONSUMER: 1
        DELETE:
          ADMIN: 0
          CONSUMER: 0
        POST:
          ADMIN: 0
        PUT:
          ADMIN: 0
      /key/refresh:
        PUT:
          ADMIN: 0
          CONSUMER: 10
      /admin/business/load:
        GET:
          ADMIN: 1
      /business/{business_id}:
        GET:
          ADMIN: 0
          CONSUMER: 1
        PUT:
          ADMIN: 1
          CONSUMER: 1
      /business:
        GET:
          ADMIN: 0
          CONSUMER: 1
        POST:
          ADMIN: 0
          CONSUMER: 1
