apiVersion: v1
kind: ConfigMap
metadata:
  name: keys-configmap
data:
  database_host: mongo-keys-service
  database_port: "27017"
  database_name: api_keys
  acl.yaml: |
    endpoints:
      /trip:
        ADMIN:
          POST: 0
      /trip/{trip_id}:
        ADMIN:
          PUT: 0
          DELETE: 0
      /trip/location/{location_id}:
        ADMIN:
          GET: 0
        CONSUMER:
          GET: 1
      /tripCount/location/{location_id}:
        ADMIN:
          GET: 0
        CONSUMER:
          GET: 1
      /key:
        ADMIN:
          POST: 0
          GET: 0
          PUT: 0
          DELETE: 0
        CONSUMER:
          GET: 1
          DELETE: 0
      /key/refresh:
        ADMIN:
          PUT: 0
        CONSUMER:
          PUT: 10
