apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.2.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              cpu: 100m
  http:
    tls:
      selfSignedCertificate:
        disabled: true
