apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-trips-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-trips-deployment
  labels:
    app: mongo-trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-trips
  template:
    metadata:
      labels:
        app: mongo-trips
    spec:
        containers:
        - name: mongo-trips
          image: ralexandre00/tripsmongo
          imagePullPolicy: Always
          ports:
          - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-trips-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-trips-secret
                key: mongo-root-password
          volumeMounts:
            - mountPath: /data/db
              name: mongo-trips-claim0
        volumes:
          - name: mongo-trips-claim0
            persistentVolumeClaim:
              claimName: mongo-trips-claim0
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-trips-service
spec:
  selector:
    app: mongo-trips
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

