apiVersion: v1
kind: Secret
metadata:
  name: mongo-trips-secret
  namespace: service
type: Opaque
data:
  mongo-root-username: SkJIUGtHSk1DOHJDU0pIakFmdGM=
  mongo-root-password: NE11VmV4QW5GR2VQa3pidXlIN0U=
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-trips-secret
  namespace: database
type: Opaque
data:
  mongo-root-username: SkJIUGtHSk1DOHJDU0pIakFmdGM=
  mongo-root-password: NE11VmV4QW5GR2VQa3pidXlIN0U=
