apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
data:
  prometheus-cm.yaml: |
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'keys-prom'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['keys-service.service:8080']

      - job_name: 'trips-prom'
        metrics_path: '/metrics'
        scrape_interval: 5s
        static_configs:
          - targets: ['trips-service.service:8080']
