# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trips.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trips.proto',
  package='trips',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btrips.proto\x12\x05trips\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n\x04Trip\x12\x1a\n\x12pickup_location_id\x18\x01 \x01(\t\x12\x1b\n\x13\x64ropoff_location_id\x18\x02 \x01(\t\x12\x33\n\x0fpickup_datetime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10\x64ropoff_datetime\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fpassenger_count\x18\x05 \x01(\x05\"T\n\x08Location\x12\x0c\n\x04zone\x18\x01 \x01(\t\x12\x0f\n\x07\x62orough\x18\x02 \x01(\t\x12\x13\n\x0blocation_id\x18\x03 \x01(\x05\x12\x14\n\x0cservice_zone\x18\x04 \x01(\t\"\x19\n\x06TripID\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\"!\n\nLocationID\x12\x13\n\x0blocation_id\x18\x01 \x01(\t\"\x93\x01\n\x1eGetCountTripsInLocationRequest\x12.\n\nstart_date\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0blocation_id\x18\x03 \x01(\t\"0\n\x1fGetCountTripsInLocationResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32\xbf\x02\n\x0cTripsService\x12\'\n\x07\x41\x64\x64Trip\x12\x0b.trips.Trip\x1a\r.trips.TripID\"\x00\x12\x37\n\x0fGetLocationById\x12\x11.trips.LocationID\x1a\x0f.trips.Location\"\x00\x12\x35\n\nRemoveTrip\x12\r.trips.TripID\x1a\x16.google.protobuf.Empty\"\x00\x12*\n\nUpdateTrip\x12\r.trips.TripID\x1a\x0b.trips.Trip\"\x00\x12j\n\x17GetCountTripsInLocation\x12%.trips.GetCountTripsInLocationRequest\x1a&.trips.GetCountTripsInLocationResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_TRIP = _descriptor.Descriptor(
  name='Trip',
  full_name='trips.Trip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pickup_location_id', full_name='trips.Trip.pickup_location_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dropoff_location_id', full_name='trips.Trip.dropoff_location_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pickup_datetime', full_name='trips.Trip.pickup_datetime', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dropoff_datetime', full_name='trips.Trip.dropoff_datetime', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passenger_count', full_name='trips.Trip.passenger_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=280,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='trips.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zone', full_name='trips.Location.zone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='borough', full_name='trips.Location.borough', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_id', full_name='trips.Location.location_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_zone', full_name='trips.Location.service_zone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=366,
)


_TRIPID = _descriptor.Descriptor(
  name='TripID',
  full_name='trips.TripID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trip_id', full_name='trips.TripID.trip_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=393,
)


_LOCATIONID = _descriptor.Descriptor(
  name='LocationID',
  full_name='trips.LocationID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location_id', full_name='trips.LocationID.location_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=428,
)


_GETCOUNTTRIPSINLOCATIONREQUEST = _descriptor.Descriptor(
  name='GetCountTripsInLocationRequest',
  full_name='trips.GetCountTripsInLocationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_date', full_name='trips.GetCountTripsInLocationRequest.start_date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='trips.GetCountTripsInLocationRequest.end_date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_id', full_name='trips.GetCountTripsInLocationRequest.location_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=578,
)


_GETCOUNTTRIPSINLOCATIONRESPONSE = _descriptor.Descriptor(
  name='GetCountTripsInLocationResponse',
  full_name='trips.GetCountTripsInLocationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='trips.GetCountTripsInLocationResponse.count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=628,
)

_TRIP.fields_by_name['pickup_datetime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TRIP.fields_by_name['dropoff_datetime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETCOUNTTRIPSINLOCATIONREQUEST.fields_by_name['start_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETCOUNTTRIPSINLOCATIONREQUEST.fields_by_name['end_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Trip'] = _TRIP
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['TripID'] = _TRIPID
DESCRIPTOR.message_types_by_name['LocationID'] = _LOCATIONID
DESCRIPTOR.message_types_by_name['GetCountTripsInLocationRequest'] = _GETCOUNTTRIPSINLOCATIONREQUEST
DESCRIPTOR.message_types_by_name['GetCountTripsInLocationResponse'] = _GETCOUNTTRIPSINLOCATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Trip = _reflection.GeneratedProtocolMessageType('Trip', (_message.Message,), dict(
  DESCRIPTOR = _TRIP,
  __module__ = 'trips_pb2'
  # @@protoc_insertion_point(class_scope:trips.Trip)
  ))
_sym_db.RegisterMessage(Trip)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'trips_pb2'
  # @@protoc_insertion_point(class_scope:trips.Location)
  ))
_sym_db.RegisterMessage(Location)

TripID = _reflection.GeneratedProtocolMessageType('TripID', (_message.Message,), dict(
  DESCRIPTOR = _TRIPID,
  __module__ = 'trips_pb2'
  # @@protoc_insertion_point(class_scope:trips.TripID)
  ))
_sym_db.RegisterMessage(TripID)

LocationID = _reflection.GeneratedProtocolMessageType('LocationID', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONID,
  __module__ = 'trips_pb2'
  # @@protoc_insertion_point(class_scope:trips.LocationID)
  ))
_sym_db.RegisterMessage(LocationID)

GetCountTripsInLocationRequest = _reflection.GeneratedProtocolMessageType('GetCountTripsInLocationRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCOUNTTRIPSINLOCATIONREQUEST,
  __module__ = 'trips_pb2'
  # @@protoc_insertion_point(class_scope:trips.GetCountTripsInLocationRequest)
  ))
_sym_db.RegisterMessage(GetCountTripsInLocationRequest)

GetCountTripsInLocationResponse = _reflection.GeneratedProtocolMessageType('GetCountTripsInLocationResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETCOUNTTRIPSINLOCATIONRESPONSE,
  __module__ = 'trips_pb2'
  # @@protoc_insertion_point(class_scope:trips.GetCountTripsInLocationResponse)
  ))
_sym_db.RegisterMessage(GetCountTripsInLocationResponse)



_TRIPSSERVICE = _descriptor.ServiceDescriptor(
  name='TripsService',
  full_name='trips.TripsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=631,
  serialized_end=950,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddTrip',
    full_name='trips.TripsService.AddTrip',
    index=0,
    containing_service=None,
    input_type=_TRIP,
    output_type=_TRIPID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLocationById',
    full_name='trips.TripsService.GetLocationById',
    index=1,
    containing_service=None,
    input_type=_LOCATIONID,
    output_type=_LOCATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveTrip',
    full_name='trips.TripsService.RemoveTrip',
    index=2,
    containing_service=None,
    input_type=_TRIPID,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTrip',
    full_name='trips.TripsService.UpdateTrip',
    index=3,
    containing_service=None,
    input_type=_TRIPID,
    output_type=_TRIP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCountTripsInLocation',
    full_name='trips.TripsService.GetCountTripsInLocation',
    index=4,
    containing_service=None,
    input_type=_GETCOUNTTRIPSINLOCATIONREQUEST,
    output_type=_GETCOUNTTRIPSINLOCATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRIPSSERVICE)

DESCRIPTOR.services_by_name['TripsService'] = _TRIPSSERVICE

# @@protoc_insertion_point(module_scope)
