spring:
  application:
    name: api-business-service
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
server:
  ssl:
    key-store: business.p12
    key-store-password: something
    key-store-type: pkcs12
    key-alias: business
    key-password: something
  port: 443