version: "3.3"

services:
  keys-service:
    restart: always
    container_name: keys_service
    build:
      context: .
      dockerfile: Dockerfile-keys
    environment:
      MONGO_DATABASE_URL: mongodb://keys_mongodb:27017
      MONGO_DATABASE_NAME: api_keys
      ACL_FILE: /home/app/acl.yaml
    volumes:
      - ./acl.yaml:/home/app/acl.yaml:ro
    depends_on:
      - keys-mongodb
    ports:
      - "8080:8080"

  keys-mongodb:
    restart: always
    container_name: keys_mongodb
    build:
      context: .
      dockerfile: Dockerfile-mongo
    environment:
      - MONGO_INITDB_DATABASE=api_keys
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: