name: Trip tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Newman dependency
        run: npm install --prefix tests/postman/

      - name: Start containers
        run: docker-compose -f "trip/docker-compose.yml" up -d --build

      - uses: matt-ball/newman-action@master
        with:
          collection: trip/tests/Trip.postman_collection.json
          environment: trip/tests/Trip.postman_environment.json

      - name: Stop containers
        run: docker-compose -f "trip/docker-compose.yml" down
