name: Value Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: value

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: value

      - name: Change wrapper permissions
        run: chmod +x gradlew

      - name: Run build with Gradle wrapper
        run: ./gradlew build --scan

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: value/build/reports/